# general settings
name: train_HAT-L_Blind_Seoul_from_ImageNet_pretrain
model_type: HATModel
scale: 4
num_gpu: auto
manual_seed: 36

# dataset and data loader settings
datasets:
  train:
    name: Seoul
    type: BlindSRDataset
    dataroot_gt: data/seoul/hr.lmdb
    io_backend:
      type: lmdb

    gt_size: 512
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 3
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

    # blind sr settings
    shuffle_prob: 0.1
    use_sharp: false
    degradation_type: bsrgan
    in_chans: 3

# network structures
network_g:
  type: HAT
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: experiments/pretrained_models/HAT-L_SRx4_ImageNet-pretrain.pth
  param_key_g: 'params_ema'
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 1e-5
    weight_decay: 0
    betas: [0.9, 0.99]
    amsgrad: true
  
  scheduler:
    type: CosineAnnealingLR
    T_max: 250000
    eta_min: !!float 1e-7

  total_iter: 250000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  pbar: False

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
